# If you'd like to support development, configure one of the platforms below
# and uncomment the relevant line. See:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [codynlab]
# ko_fi: codynlab
# custom: ['https://codynlab.dev']
